#%RAML 1.0 NamedExample
value:
  -
    name: Name1
    type: business
    address: "1 StreetOne, CountryOne"
    airMiles: 2000
  - 
    name: Name2
    type: personal
    address: "2 StreetTwo, CountryTwo"
    airMiles: 10000